# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170725_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmodel',
            name='image',
            field=models.ImageField(default='app/static/app/goods_pic_folder/no-img.jpg', upload_to='app/static/app/goods_pic_folder'),
        ),
    ]
