# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170725_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmodel',
            name='image',
            field=models.ImageField(default='static/goods_pic_folder/no-img.jpg', upload_to='static/goods'),
        ),
    ]
