# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170725_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='reviewer_answer',
            field=models.CharField(default='', max_length=512),
        ),
    ]
