# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reviewmodel_reviewer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviewer_answer',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
